name: flutter_app
description: NTUT Life TAT, convenient, concise, fast, powerful, enrich your NTUT life!
publish_to: 'none'

# CHECK THE BUILD CODE BEFORE DISTRIBUTION!!
version: 1.0.6

environment:
  flutter: ">=3.16.9 <4.0.0"
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # TAT 2 Core implementations, reference it to use some of the new features.
  # Use https login with GitHub personal access key at the first time to obtain this sub-package.
  tat_core:
    git:
      url: git@github.com:NTUT-NPC/TAT-Core.git
      ref: 24ec4a1614758f1646c2271db7e495a0362486ee

  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  url_launcher: ^6.2.4
  logger: ^2.0.2+1
  sprintf: ^7.0.0
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  video_player: ^2.8.2
  chewie: ^1.7.4
  android_intent_plus: ^4.0.3
  html_unescape: ^2.0.0
  local_auth: ^2.1.8
  version: ^3.0.2
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  html: ^0.15.4
  connectivity_plus: ^5.0.2
  github: ^9.22.0
  clipboard: ^0.1.3
  flutter_inappwebview: ^6.0.0
  flutter_web_browser:
    git:
      url: git@github.com:NEO-TAT/flutter_web_browser.git
      ref: master
  eva_icons_flutter: ^3.1.0
  flutter_feather_icons: ^2.0.0+1
  json_annotation: ^4.8.1
  back_button_interceptor: ^7.0.1
  dart_big5: ^0.0.5
  package_info_plus: ^5.0.1
  flutter_widget_from_html_core: ^0.14.11
  flutter_staggered_animations: ^1.1.1
  flutter_downloader: ^1.11.6
  permission_handler: ^11.2.0
  mime_type: ^1.0.0
  get: ^4.6.6
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  auto_size_text: ^3.0.0
  table_calendar: ^3.0.0-nullsafety.1
  fluttertoast: ^8.2.4
  awesome_dialog: ^3.2.0
  flutter_slidable: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_markdown: ^0.6.18+3
  numberpicker: ^2.1.2
  alice_lightweight: ^3.5.1
  open_filex: ^4.4.0
  modal_bottom_sheet: ^3.0.0-pre # restricted by flutter sdk. (package import conflict)
  email_validator: ^2.1.17
  weekday_selector: ^1.1.0
  device_info_plus: ^9.1.2

  meta: ^1.10.0
  uuid: ^4.3.3
  intl_utils: ^2.8.7
  flutter_native_splash: ^2.3.10
  multi_select_flutter: ^4.1.3
  share_plus: ^7.2.2
  file_picker: ^6.1.1
  flutter_install_app: ^1.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  dependency_validator: ^3.2.3

  #  flutter_launcher_icons: ^0.11.0 Restricted by flutter_native_splash. Enable it if you want to use it.
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: TATFont
      fonts:
        - asset: assets/fonts/GenSenRounded-R.ttc
          weight: 400
        - asset: assets/fonts/GenSenRounded-B.ttc
          weight: 700

flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tat.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png

  color_dark: "#2b2b2b"
  image_dark: assets/images/splash-dark.png

  android: true
  android_gravity: center

  ios: true
  ios_content_mode: center

  fullscreen: true

module:
  androidX: true
